### ISSUE TITLE
Unmodified code but runtime error

### ISSUE THREAD

**Issue by mengweiwang** [suro119/CAE#1]
**file:** models/entropy_networks.py
**35 lines:** log_probs = gsm.log_prob(x)
**error:** The right-most size of value must match event_shape: torch.Size([32, 96, 256]) vs torch.Size([1]).
I encountered the error when executing this line of code. Did you pass the execution?

**Comment by suro119** [comment]
Thank you for your interest! However this is a old research project and the repository is not being maintained anymore. Please refer to [this paper](http://arxiv.org/abs/1802.01436) for a better implementation of the entropy model.
